apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | default "8Gi" }}   # Sử dụng 8Gi làm giá trị mặc định
  storageClassName: {{ .Values.mysql.persistence.storageClass | default "standard" }}
