apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
